POST http://localhost:5678/users
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="name"

admin
--WebAppBoundary--

###
GET http://localhost:5678/users/1/posts

###
GET http://localhost:5678/users/1

###